[source]
git = "https://github.com/RustPython/RustPython"
#branch = "redox-release"
rev="0717d5a33146136727ac315deea3f967fc2c00f6"

[build]
dependencies = [
  "openssl1",
  "zlib",
  "relibc"
]
template = "cargo"
