[source]
tar = "https://ftp.mozilla.org/pub/firefox/releases/136.0.2/source/firefox-136.0.2.source.tar.xz"
blake3 = "7d4ab084f537dc9972ca87a81219149027737666f987fc5d3c29721b151708b6"
#patches = [
#    "./01_redox.patch"
#]

[build]
template = "custom"
dependencies = [
#    "curl",
#    "expat",
#    "libjpeg",
#    "libpng",
#    "nghttp2",
#    "openssl1",
#    "sdl1",
#    "zlib",
#    "freetype2",
#    "liborbital",
#    "libiconv",
#    "openssl1",
    "pango",
    "rustpython",
    "oss",
]

# copy-pasted from configure template
pre-script = """
# Common pre script
# Add cookbook bins to path
export PATH="${COOKBOOK_ROOT}/bin:${PATH}"

# This adds the sysroot includes for most C compilation
#TODO: check paths for spaces!
export CFLAGS="-I${COOKBOOK_SYSROOT}/include"
export CPPFLAGS="-I${COOKBOOK_SYSROOT}/include"

# This adds the sysroot libraries and compiles binaries statically for most C compilation
#TODO: check paths for spaces!
export LDFLAGS="-L${COOKBOOK_SYSROOT}/lib --static"

# These ensure that pkg-config gets the right flags from the sysroot
export PKG_CONFIG_ALLOW_CROSS=1
export PKG_CONFIG_PATH=
export PKG_CONFIG_LIBDIR="${COOKBOOK_SYSROOT}/lib/pkgconfig"
export PKG_CONFIG_SYSROOT_DIR="${COOKBOOK_SYSROOT}"

# configure template
COOKBOOK_CONFIGURE="${COOKBOOK_SOURCE}/configure"
COOKBOOK_CONFIGURE_FLAGS=(
    --host="${TARGET}"
    --prefix=""
    --disable-shared
    --enable-static
)
COOKBOOK_MAKE="make"
COOKBOOK_MAKE_JOBS="$(nproc)"
function cookbook_configure {
    "${COOKBOOK_CONFIGURE}" "${COOKBOOK_CONFIGURE_FLAGS[@]}"
    "${COOKBOOK_MAKE}" -j "${COOKBOOK_MAKE_JOBS}"
    "${COOKBOOK_MAKE}" install DESTDIR="${COOKBOOK_STAGE}"
}
"""

script = """
export MOZCONFIG="${COOKBOOK_RECIPE}/mozconfig"
rsync -a --delete "${COOKBOOK_SOURCE}/" ./
PS4='+ $(basename "$0"):$LINENO: '

./mach build -v
false
"""

[package]
shared-deps = [
    # XXX: currently only the following are dynamically linked
    #"curl",
#    "libgcc",
#    "libiconv",
#    "liborbital",
#    "libpng",
#    "nghttp2",
#    "openssl1",
    "relibc",
#    "zlib",
]
dependencies = [
    "ca-certificates",
    "orbital",
]
