
[source]
tar = "https://tar.goaccess.io/goaccess-1.9.4.tar.gz"
patches = [
    "0001-Ensure-fixed-width-integers-and-PIPE_BUF-are-defined.patch",
    "0002-Add-option-to-ignore-building-bin2c.patch",
]

[build]
dependencies = ["ncursesw"]
template = "custom"
script = """
export COOKBOOK_NOSTRIP=1

# Generate the make files
cd "$COOKBOOK_SOURCE"
autoreconf -fiv
automake --add-missing --copy --force-missing

# Copy the sources
mkdir -p "$COOKBOOK_BUILD"
cd "$COOKBOOK_BUILD"
rsync -a --delete "${COOKBOOK_SOURCE}/" .

# Compile bin2c
gcc -O2 -o "$COOKBOOK_BUILD/bin2c" "$COOKBOOK_SOURCE/src/bin2c.c"
chmod +x "$COOKBOOK_BUILD/bin2c"

# Configure for cross-compilation
export CFLAGS="-I/mnt/redox/cookbook/recipes/libs/ncursesw/target/$ARCH-unknown-redox/stage/usr/include"
export LDFLAGS="-L/mnt/redox/cookbook/recipes/libs/ncursesw/target/$ARCH-unknown-redox/stage/usr/lib"

./configure \
    --host=$ARCH-unknown-redox \
    --enable-utf8 \
    --disable-geoip \
    --prefix=/usr \
    --disable-dependency-tracking \
    --with-bin2c-path="$COOKBOOK_BUILD/src/bin2c"
    
# Build
make

# Install
mkdir -p "$COOKBOOK_STAGE/usr/bin"
cp "$COOKBOOK_BUILD/goaccess" "$COOKBOOK_STAGE/usr/bin/"
"""

