[source]
git = "https://github.com/willnode/rustysd"
[build]
template = "custom"
script = """
cookbook_cargo

mkdir -p ${COOKBOOK_STAGE}/etc/rustysd/system
cat <<'EOF' > ${COOKBOOK_STAGE}/etc/rustysd/rustysd_config.toml
unit_dirs = [
  "/etc/rustysd/system",
  "/etc/rustysd/user",
]
logging_dir = "/var/log/rustysd"
log_to_disk = true
log_to_stdout = false
target_unit = "default.target"
# selfpath = ""
# notifications_dir = ""
EOF

cp ${COOKBOOK_SOURCE}/docker_test_units/*.target ${COOKBOOK_STAGE}/etc/rustysd/system/
"""
