[source]
git = "https://gitlab.redox-os.org/redox-os/llvm-project.git"
upstream = "https://github.com/rust-lang/llvm-project.git"
branch = "redox-2024-05-11"

[build]
template = "custom"
dependencies = [
    "zlib",
    "zstd"
]
script = """
DYNAMIC_INIT

COOKBOOK_CONFIGURE="cmake"
COOKBOOK_CONFIGURE_FLAGS=(
    -DCMAKE_AR="$(which "${TARGET}-ar")"
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CROSSCOMPILING=True
    -DCMAKE_CXX_FLAGS="--std=gnu++11"
    -DCMAKE_EXE_LINKER_FLAGS="-static"
    -DCMAKE_RANLIB="$(which "${TARGET}-ranlib")"
    -DCMAKE_INSTALL_PREFIX="/usr"
    -DCMAKE_INSTALL_INCLUDEDIR="include"
    -DCMAKE_INSTALL_OLDINCLUDEDIR="/include"
    -DCMAKE_SYSTEM_NAME=Generic
    -DCROSS_TOOLCHAIN_FLAGS_NATIVE="-DCMAKE_TOOLCHAIN_FILE=$(realpath "${COOKBOOK_RECIPE}/native.cmake")"
    -DLLVM_BUILD_BENCHMARKS=OFF
    -DLLVM_BUILD_EXAMPLES=OFF
    -DLLVM_BUILD_TESTS=OFF
    -DLLVM_BUILD_UTILS=OFF
    -DLLVM_DEFAULT_TARGET_TRIPLE="${TARGET}"
    -DLLVM_ENABLE_LTO=OFF
    -DLLVM_ENABLE_PROJECTS=clang
    -DLLVM_ENABLE_RTTI=ON
    -DLLVM_ENABLE_THREADS=ON
    -DLLVM_ENABLE_ZLIB=ON
    -DLLVM_ENABLE_ZSTD=OFF
    -DLLVM_INCLUDE_BENCHMARKS=OFF
    -DLLVM_INCLUDE_EXAMPLES=OFF
    -DLLVM_INCLUDE_TESTS=OFF
    -DLLVM_INCLUDE_UTILS=OFF
    -DLLVM_TARGET_ARCH="$(echo "${TARGET}" | cut -d - -f1)"
    -DLLVM_TARGETS_TO_BUILD=X86 # TODO: get from TARGET
    -DLLVM_TOOL_LLVM_COV_BUILD=OFF
    -DLLVM_TOOL_LLVM_LTO_BUILD=OFF
    -DLLVM_TOOL_LLVM_LTO2_BUILD=OFF
    -DLLVM_TOOL_LLVM_PROFDATA_BUILD=OFF
    -DLLVM_TOOL_LLVM_RTDYLD_BUILD=OFF
    -DLLVM_TOOL_LLVM_XRAY_BUILD=OFF
    -DLLVM_TOOL_LLI_BUILD=OFF
    -DLLVM_TOOL_LTO_BUILD=OFF
    -DLLVM_TOOLS_INSTALL_DIR=bin
    -DLLVM_UTILS_INSTALL_DIR=bin
    -DPYTHON_EXECUTABLE="/usr/bin/python2"
    -DUNIX=1
    -DZLIB_LIBRARY=-lz
    -DZLIB_INCLUDE_DIR="${COOKBOOK_SYSROOT}/include"
    -Wno-dev
)
#LLVM_TABLEGEN="$(which llvm-tblgen-18 || true)"
#if [ -n "${LLVM_TABLEGEN}" ]
#then
#    COOKBOOK_CONFIGURE_FLAGS+=(-DLLVM_TABLEGEN="${LLVM_TABLEGEN}")
#fi
COOKBOOK_CONFIGURE_FLAGS+=("${COOKBOOK_SOURCE}/llvm")

export LDFLAGS="-L${COOKBOOK_SYSROOT}/lib -Wl,-rpath-link,${COOKBOOK_SYSROOT}/lib"


# These ensure that pkg-config gets the right flags from the sysroot
export PKG_CONFIG_ALLOW_CROSS=1
export PKG_CONFIG_PATH=
export PKG_CONFIG_LIBDIR="${COOKBOOK_SYSROOT}/lib/pkgconfig"
export PKG_CONFIG_SYSROOT_DIR="${COOKBOOK_SYSROOT}"

#set -x
cookbook_configure
#set +x
"""
