[source]
git = "https://gitlab.redox-os.org/redox-os/rust.git"
branch = "redox-2025-01-12"
# due to heavy git operation, this will only clone once and will not refetch
# if you want to refetch or changing the branch, please do ucr.rust
shallow_clone = true

[build]
template = "custom"
dependencies = [
    "llvm18",
    "zlib"
]
script = """
DYNAMIC_INIT
unset AR AS CC CXX LD NM OBJCOPY OBJDUMP RANLIB READELF STRIP
export MAGIC_EXTRA_RUSTFLAGS="-C link-args=-lz"
python3 "${COOKBOOK_SOURCE}/x.py" install --config "${COOKBOOK_RECIPE}/config.toml" --jobs $(nproc) --incremental

rsync -av --delete "${COOKBOOK_SOURCE}"/install/* "${COOKBOOK_STAGE}/"
# Cannot use STRIP because it is unset previously
"${HOST}-strip" -v "$1/bin/rustc"
# TODO: rustdoc
"""

[package]
dependencies = [
    "gcc13",
    "cargo"
]
# TODO: Not implemented
# version_script = """
# printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
# """
