[source]
git = "https://github.com/TheWaWaR/simple-http-server"
patches = [
    "redox.patch"
]

[build]
template = "custom"
dependencies = [
    "openssl1",
]
script = """
DYNAMIC_INIT
cookbook_cargo
"""
