#TODO Go 1.4 is the last compiling version from CC
#TODO Still not compiling: duplicate symbol main in runtime and runtime.a(rt0_redox_amd64.)
#TODO see ../go for guide to compile newer versions
[source]
tar = "https://go.dev/dl/go1.4.3.src.tar.gz"
patches = [
   "01_redox.patch"
]

[build]
template = "custom"
script = """

# Go does not support out-of-tree builds :(
rsync -av --delete "${COOKBOOK_SOURCE}/" ./

export GOROOT_FINAL=${COOKBOOK_STAGE}
export GOHOSTARCH=amd64
export CGO_ENABLED=0
export GOOS=redox
export GOARCH=amd64
# Go can't recognize these flags?
# export GO_CCFLAGS=${CFLAGS}
# export GO_LDFLAGS=${LDFLAGS}
export CC_FOR_TARGET="${CC}"
export CXX_FOR_TARGET="${CXX}"
# Don't poison the runtime tools (host -> host)
unset AR AS CC CXX LD LDFLAGS NM OBJCOPY OBJDUMP RANLIB READELF STRIP

cd ./src && ./all.bash
"""
